name: "Build"
on:
  push:
jobs:
  nixos-20-09:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - uses: cachix/cachix-action@v8
      with:
        name: pietdevries94
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: mkdir -p ~/.config/nixpkgs && echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix
    - run: nix-build