name: "Build"
on:
  push:
jobs:
  nixos-20-03:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-20.03
    - uses: cachix/cachix-action@v6
      with:
        name: pietdevries94
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: mkdir -p ~/.config/nixpkgs && echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix
    - run: nix-build